const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.wrap,
		C3.Plugins.Spritefont2,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Particles,
		C3.Plugins.Button,
		C3.Behaviors.Flash,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.ScriptsInEvents.FolhaFase2_Event14_Act1,
		C3.ScriptsInEvents.FolhaFase2_Event15
	];
};
self.C3_JsPropNameTable = [
	{Fixar: 0},
	{planoDeFundo: 0},
	{cola: 0},
	{Sólido2: 0},
	{Sprite2: 0},
	{Sólido: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{engenheiro: 0},
	{Teclado: 0},
	{Toque: 0},
	{Áudio: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Âncora: 0},
	{DarAVolta: 0},
	{relogio: 0},
	{Sprite29: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{gameOver: 0},
	{FonteDeSprites: 0},
	{Sprite36: 0},
	{voltar: 0},
	{Mouse: 0},
	{Sprite37: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite38: 0},
	{Sprite40: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{Sprite28: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{Sprite39: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{InformaçãoDaPlataforma: 0},
	{Sprite43: 0},
	{Texto: 0},
	{Sprite44: 0},
	{Partículas: 0},
	{Botão: 0},
	{Sprite45: 0},
	{Sprite27: 0},
	{Sprite46: 0},
	{Sprite47: 0},
	{Piscar: 0},
	{Luz: 0},
	{txtAviso: 0},
	{time1: 0},
	{TempoRestante: 0}
];

self.InstanceType = {
	planoDeFundo: class extends self.ITiledBackgroundInstance {},
	cola: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	engenheiro: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Toque: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	relogio: class extends self.ITextInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	gameOver: class extends self.ITextInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	voltar: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	InformaçãoDaPlataforma: class extends self.IInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Partículas: class extends self.IParticlesInstance {},
	Botão: class extends self.IButtonInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Luz: class extends self.ISpriteInstance {},
	txtAviso: class extends self.ITextInstance {}
}